name: Set issue label and project to Meetings
on:
  issues:
    types: [opened, labeled]

jobs:
  set-label:
    name: Set label of Meeting issues to meetings
    runs-on: ubuntu-latest
    steps:
      - uses: Naturalclar/issue-action@v2.0.2
        with:
          title-or-body: "title"
          parameters: '[ {"keywords": ["Meeting"], "labels": ["meetings"]}]'
          github-token: "${{ secrets.GITHUB_TOKEN }}"
  assign-project:
    name: Set project of Meeting issues to Meetings
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    runs-on: ubuntu-latest
    steps:
      - uses: srggrs/assign-one-project-github-action@1.2.0
        if: |
          contains(github.event.issue.title, 'Meeting')
        with:
          project: 'https://github.com/stefanocoretta/ling-systems/projects/1'
          column_name: 'Next'
