name: "Set label and project to meetings in issues"
on:
  issues:
    types: [opened, labeled]

jobs:
  set-label:
    name: Set label of "Minutes" issues to Meetings
    runs-on: ubuntu-latest
    steps:
      - uses: Naturalclar/issue-action@v2.0.2
        with:
          title-or-body: "title"
          parameters: '[ {"keywords": ["Minutes"], "labels": ["meetings"]}]'
          github-token: "${{ secrets.GITHUB_TOKEN }}"
  assign-project:
    name: Set project to Meetings
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    runs-on: ubuntu-latest
    steps:
    - name: Assign "Minutes" issues to Meetings
      uses: srggrs/assign-one-project-github-action@1.2.0
      if: |
        contains(github.event.issue.title, 'Minutes')
      with:
        project: 'https://github.com/stefanocoretta/resrepo-template/projects/1'
        column_name: 'Next'
